server:
  port: 8888
  servlet:
    context-path: /config/

spring:
  application:
    name: config-server
  config:
    import: "classpath:application.yml"

  cloud:
    config:
      server:
        git:
          uri: https://github.com/meirafa/configCloudPi

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
info:
  author: Projeto final backend - Grupo 2
