server:
  port: 8080

spring:
  config:
    import: optional:configserver:http://localhost:8888/
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**, /login/**
        - id: account
          uri: lb://account
          predicates:
            - Path=/account/**, /cards/**

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
