server:
  port: 8086
  servlet:
    context-path: /user/

spring:
  application:
    name: user
  config:
    import: optional:configserver:http://config:8888/
    activate:
      on-profile: "dev"

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://host.docker.internal:3306/user
    # username: root
    # password: root
    # url: jdbc:mysql://localhost:3306/pi_final_g2
    # username: user
    # password: password
    url: jdbc:mysql://root@localhost:3306/pi_final_g2
    username: dh
    password: 123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    instance-id: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
